spring:
  application:
    name: one-team
  profiles:
    active: prod
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 SQL 日志
  mapper-locations: classpath*:mapper/**/*.xml